<script src="https://giscus.app/client.js"
        data-repo="panoptic-labs/docs"
        data-repo-id="R_kgDOH9NNlw"
        data-category="Announcements"
        data-category-id="DIC_kwDOH9NNl84ChXl2"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="purple_dark"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
