name: Update recent blog posts and deploy

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn

    - name: Generate recent updates
      run: node generateRecentUpdates.js

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Set this in your repo's secrets
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions, do not need to set
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Set this in your repo's secrets
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Set this in your repo's secrets
        vercel-args: '--prod'